config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :users
  resources :categories
  resources :books
  resources :chapters, only: [:create]
  resources :parts, only: [:create]
  get 'editor/:id', to: 'editor#index', as: :editor

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :chapters
  has_many :parts
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  has_many :books
  before_create :assign_slug

  def assign_slug
    categories = Category.where(['title = ?', title])
    self.slug = if categories.size > 0
                  "#{title.parameterize}-#{categories.size}"
                else
                  title.parameterize
                end
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book, optional: true
  belongs_to :part, optional: true
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :book
  has_many :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index; end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @categories = Category.all.order(title: :asc)
  end

  def create∆
    categories = Category.find(params[:book][:category_ids])
    @book = Book.new(book_params)
    @book.categories = categories
    if @book.save
      redirect_to edit_book_path @book
    else
      render :new
    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :isbn, :description, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def create
    book = Book.find(params[:book]) if params[:book]
    @part = Part.find(params[:part]) if params[:part]
    @chapter = Chapter.new(title: 'Chapter', book: book, part: @part)
  end

  def update; end
  def destroy; end

end

app/controllers/concerns/roman_number.rb
module RomanNumber
  def to_roman(num)
    result = ""
    number = num
    roman_mapping.keys.each do |divisor|
      quotient, modulus = number.divmod(divisor)
      result << roman_mapping[divisor] * quotient
      number = modulus
    end
    result
  end

  private

  def roman_mapping
    {
      1000 => "M",
      900 => "CM",
      500 => "D",
      400 => "CD",
      100 => "C",
      90 => "XC",
      50 => "L",
      40 => "XL",
      10 => "X",
      9 => "IX",
      5 => "V",
      4 => "IV",
      1 => "I"
    }
  end
end

app/controllers/editor_controller.rb
class EditorController < ApplicationController
  layout 'editor'

  def index
    @book = Book.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
    @categories = Category.all.order(title: :desc).limit(12)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  include RomanNumber

  def create
    book = Book.find params[:book]
    r = to_roman(params[:partsize].to_i + 1)
    @part = Part.create(title: "Part #{r}", book:book)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/books/new.html.erb
<div class="row">
  <div class="col-12 col-md-6 col-lg-6 offset-md-3 offset-lg-3">
    <div class="card border-0 shadow-sm">
      <div class="card-body p-3">
        <%= form_with model: @book do |f| %>

          <div class="mt-3">
            <%= f.label :title, class: 'form-label'  %>
            <%= f.text_field :title, placeholder: 'Book title', class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= f.label :isbn, class: 'form-label text-uppercase'  %>
            <%= f.text_field :isbn, placeholder: 'ISBN', class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= f.label :description, class: 'form-label'  %>
            <%= f.text_area :description, placeholder: 'Book description', class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= f.label 'Categories', class: 'form-label'  %>
            <%= f.select :category_ids,
                         nested_set_options(Category) {|i| "#{'-' * i.level } #{i.title}" },
                         { include_hidden: false }, { multiple: true } %>
          </div>

          <div class="my-4">
            <%= f.submit 'Create Book', class: 'btn btn-primary' %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-8">
    <div class="card border-0 shadow-sm">
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <img src="https://via.placeholder.com/400x500" alt="" class="img-fluid">
            <%= link_to 'Write Book', editor_path(@book), class: 'btn btn-primary' %>
          </div>
          <div class="col-8">
            <h4> <%= @book.title %> </h4>
            <p class="mt-4"><%= @book.description %></p>
            <ul>
              <% @book.chapters.each do |chapter| %>
                <li><%= chapter.title %></li>
              <% end %>
            </ul>

            <% @book.parts.each do |part| %>
              <p><%= part.title %></p>
              <ul>
                <% part.chapters.each do |chapter| %>
                  <li><%= chapter.title %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <% @categories.each do |category| %>
    <div class="col-6 col-md-3">
      <%= link_to category, class: 'text-decoration-none' do %>
          <div class="card border-0 mb-3 shadow-sm p-3">
            <div class="card-body">
              <h6 class="text-center"><%= category.title %></h6>
            </div>
          </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-12 col-md-8">
    <div class="card border-0 shadow-sm">
      <div class="card-body">
       <h5> <%= @category.title %> </h5>
      </div>
    </div>
  </div>

  <div class="col-12 col-md-4">
    <div class="card border-0 shadow-sm">
      <div class="card-body">
        <h5>Related Books</h5>
      </div>
    </div>
  </div>
</div>

app/views/chapters/_chapter.html.erb
<a href="#chapter-<%= @chapter.id %>"
   class="list-group-item border-0 py-2 list-group-item-action">
  <%= @chapter.title %>
</a>

app/views/chapters/create.js.erb
$(`#list-group-<%= @part.id %>`).append("<%= j(render partial: 'chapter') %>")

app/views/editor/index.html.erb
<div class="container-fluid">
  <div class="sidenav">
    <div class="nav-header">
      <h4>GoodBook</h4>
    </div>
    <div class="actions">
      Add new <a href="#">Chapter</a> or <a href="#">part</a>
    </div>
    <div class="content">

    </div>
  </div>
  <div class="main">
    <div class="row">
     <div class="col">
       <div class="d-inline-flex align-items-center" id="rightSidenavBtn" data-open="true">
         <i class="bi bi-arrow-left-circle"></i>
         <div class="ms-3"><%= @book.title %></div>
       </div>
     </div>

    </div>

    <div class="row">
      <div class="draggable-container">
        <div class="transition-wrapper">
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="carouselSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://via.placeholder.com/1500x500" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://via.placeholder.com/1500x500" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://via.placeholder.com/1500x500" class="d-block w-100" alt="...">
    </div>
  </div>
</div>

<div class="row mt-5">
  <div class="col-6">
    <h2>Popular Books</h2>
  </div>
  <div class="col-6">
    <%= link_to 'New book', new_book_path, class: 'btn btn-primary float-end' %>
  </div>
</div>

<!--Books-->
<div class="row mt-3">
  <% @books.each do |book| %>
    <div class="col-4 col-md-2 col-lg-2">
      <%= link_to book, class: 'text-decoration-none' do %>
        <div class="card border-0 shadow-sm ">
          <img src="https://via.placeholder.com/150x150" alt="">
          <div class="card-body">
            <div class="text-dark"><%= book.title %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!--Categories-->

<div class="row mt-5">
  <div class="col-12">
    <h2>Categories</h2>
  </div>
</div>


<div class="row mt-3">
  <% @categories.each do |category| %>
    <div class="col-4 col-md-2 col-lg-2">
      <%= link_to category, class:'text-decoration-none' do %>
        <div class="card border-0 shadow-sm mb-3 p-2">
          <div class="card-body">
            <h6 class="text-center text-dark"><%= category.title %></h6>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoodBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <%= render 'layouts/shared/navbar' %>
    </header>
    <main class="container mt-3">
      <% if alert %>
        <div class="alert alert-primary" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>

<!--  <footer class="he bg-white">-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-3">-->
<!--          <h3>GoodBook</h3>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </footer>-->

  </body>
</html>

app/views/layouts/editor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Editor - GoodBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="height: 100vh; min-height: 100vh; max-height: 100vh">
    <main class="container-fluid h-100">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white text-dark shadow-sm py-3">
  <div class="container">
    <%= link_to 'GoodBook', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: 'nav-link' %>
        </li>
      </ul>

      <form class="d-none d-md-block w-50 mx-auto" role="search">
        <div class="input-group">
          <span class="input-group-text" id="search-addon">
            <i class="bi bi-search fw-semibold text-primary"></i>
          </span>
          <input type="text" class="form-control"
                 placeholder="Search books"
                 aria-label="Search"
                 aria-describedby="search-addon">
          <button class="btn btn-primary" type="submit">Search</button>
        </div>
      </form>

      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Signin', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/parts/_part.html.erb
<div class="accordion mt-3" id="part-<%= @part.id %>">
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading<%= @part.id %>">
      <button class="accordion-button" type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapse-<%= @part.id %>"
              aria-expanded="true"
              aria-controls="collapse-<%= @part.id %>">
        <%= @part.title %>
      </button>
    </h2>
    <div id="collapse-<%= @part.id %>" class="accordion-collapse collapse show"
         aria-labelledby="heading<%= @part.id %>"
         data-bs-parent="#part-<%= @part.id %>">

      <div class="accordion-body p-0">
        <div class="list-group">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/parts/create.js.erb
$('#part-container').append("<%= j(render partial: 'parts/part') %>")